-- FerrumIT Market Rate Analysis Migration
-- Run in Supabase SQL Editor

-- 1. Market rate analyses table
CREATE TABLE IF NOT EXISTS market_rate_analyses (
  id                 uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  zip                text,
  city               text NOT NULL,
  state              text NOT NULL,
  col_index          numeric,
  median_income      numeric,
  unemployment_rate  numeric,
  market_tier        text NOT NULL DEFAULT 'standard',
  pricing_multiplier numeric NOT NULL DEFAULT 1.0,
  rates              jsonb NOT NULL DEFAULT '{}',
  afterhours_rates   jsonb,
  market_notes       text,
  analysis_source    text NOT NULL DEFAULT 'ai_generated',
  analyzed_at        timestamptz NOT NULL DEFAULT now(),
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE(city, state)
);

-- 2. Quote rate sheets table
CREATE TABLE IF NOT EXISTS quote_rate_sheets (
  id             uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  quote_id       uuid REFERENCES quotes(id) ON DELETE CASCADE,
  analysis_id    uuid REFERENCES market_rate_analyses(id),
  market_zip     text,
  market_city    text,
  market_state   text,
  accepted_rates jsonb NOT NULL,
  overrides      jsonb NOT NULL DEFAULT '{}',
  accepted_by    uuid REFERENCES profiles(id),
  accepted_at    timestamptz NOT NULL DEFAULT now(),
  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE(quote_id)
);

-- 3. RLS policies
ALTER TABLE market_rate_analyses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated read market analyses" ON market_rate_analyses;
DROP POLICY IF EXISTS "Authenticated write market analyses" ON market_rate_analyses;
CREATE POLICY "Authenticated read market analyses"   ON market_rate_analyses FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated write market analyses"  ON market_rate_analyses FOR ALL    TO authenticated USING (true) WITH CHECK (true);

ALTER TABLE quote_rate_sheets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated manage rate sheets" ON quote_rate_sheets;
CREATE POLICY "Authenticated manage rate sheets" ON quote_rate_sheets FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 4. Seed data (61 markets from Excel v4 Apr 2026)
INSERT INTO market_rate_analyses (state, city, col_index, median_income, unemployment_rate, market_tier, pricing_multiplier, rates, market_notes, analysis_source, analyzed_at)
VALUES
  ('AL', 'Mobile', 83.0, 44780.0, 6.2, 'secondary', 0.845, '{"remote_support": 140.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 190.0, "design_ux": 125.0, "pc_setup": 225.0}', 'Onboard: Waive/defer  |  Deep secondary market. State CoL index ~88, Mobile city even lower at ~83. Port and military economy with modest SMB density. Lead with ransomware and supply-chain risk for manufacturing clients. Price at near-floor to establish presence.', 'imported', now()),
  ('AZ', 'Phoenix', 106.0, 64000.0, 4.8, 'standard', 1.0, '{"remote_support": 160.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 220.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Fast-growing Sun Belt metro. CoL near national average. Competitive MSP market with tech-sector growth (Intel, TSMC expansion). Cybersecurity awareness is high — compete on SOC maturity and 24x5 coverage. No state income tax keeps client budgets flexible.', 'imported', now()),
  ('CA', 'Cathedral City', 116.0, 53000.0, 7.5, 'standard', 1.0465, '{"remote_support": 165.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 230.0, "design_ux": 145.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Inland Empire / Coachella Valley market. CoL above national but income modest. Desert resort economy with thin margins. Full rate supportable with risk/ROI framing for hospitality and healthcare clients.', 'imported', now()),
  ('CA', 'Los Angeles', 173.0, 68000.0, 5.8, 'premium', 1.2326, '{"remote_support": 210.0, "onsite_block_2hr": 380.0, "onsite_additional": 175.0, "dev_crm": 300.0, "design_ux": 185.0, "pc_setup": 300.0}', 'Onboard: Standard  |  Major metro — 73% above national CoL. Area 2 surcharge on all on-site labor. Dense MSP competition; differentiate on cybersecurity depth and response SLAs. Entertainment and media clients have high IP-protection sensitivity.', 'imported', now()),
  ('CA', 'Oakland', 160.0, 76000.0, 6.5, 'premium', 1.2016, '{"remote_support": 200.0, "onsite_block_2hr": 380.0, "onsite_additional": 175.0, "dev_crm": 285.0, "design_ux": 175.0, "pc_setup": 300.0}', 'Onboard: Standard  |  Bay Area adjacent. Area 2 surcharge on all on-site labor. High CoL and tech-adjacent buyer base. Strong cybersecurity awareness — buyers compare on EDR depth and SOC maturity, not just price.', 'imported', now()),
  ('CA', 'Palm Springs', 130.0, 58000.0, 6.5, 'standard', 1.0465, '{"remote_support": 180.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 250.0, "design_ux": 155.0, "pc_setup": 275.0}', 'Onboard: Standard  |  Desert resort market. CoL 30% above national; income modest. Tourism and hospitality clients have thin margins — lead with business continuity and PCI compliance framing.', 'imported', now()),
  ('CA', 'San Diego', 160.0, 90000.0, 4.5, 'premium', 1.2016, '{"remote_support": 200.0, "onsite_block_2hr": 380.0, "onsite_additional": 175.0, "dev_crm": 285.0, "design_ux": 175.0, "pc_setup": 300.0}', 'Onboard: Standard  |  Area 2 surcharge on all on-site labor. Strong defense/biotech/healthcare buyer base — CMMC and HIPAA compliance framing is highly effective. Competitive market but buyers value depth.', 'imported', now()),
  ('CA', 'San Francisco', 213.0, 126000.0, 5.4, 'premium', 1.3566, '{"remote_support": 245.0, "onsite_block_2hr": 380.0, "onsite_additional": 175.0, "dev_crm": 350.0, "design_ux": 210.0, "pc_setup": 325.0}', 'Onboard: Standard  |  Most expensive market in portfolio. Area 2 surcharge on all on-site labor. SF buyers expect enterprise-grade tooling and rapid response. Price on high end — buyers compare on SLAs and security maturity.', 'imported', now()),
  ('CA', 'Santa Clara', 195.0, 130000.0, 4.2, 'premium', 1.3101, '{"remote_support": 230.0, "onsite_block_2hr": 380.0, "onsite_additional": 175.0, "dev_crm": 330.0, "design_ux": 200.0, "pc_setup": 325.0}', 'Onboard: Standard  |  Silicon Valley core. Area 2 surcharge on all on-site labor. Highest median income in portfolio. Tech buyers are security-savvy; compete on EDR depth, SOC maturity, and response SLAs.', 'imported', now()),
  ('CA', 'Santa Monica', 195.0, 100000.0, 5.0, 'premium', 1.2791, '{"remote_support": 230.0, "onsite_block_2hr": 380.0, "onsite_additional": 175.0, "dev_crm": 330.0, "design_ux": 200.0, "pc_setup": 325.0}', 'Onboard: Standard  |  LA metro premium submarket. Area 2 surcharge on all on-site labor. Entertainment and creative-tech clients have high data sensitivity — lead with ransomware and IP protection framing.', 'imported', now()),
  ('CA', 'West Sacramento', 132.0, 62000.0, 6.5, 'standard', 1.0465, '{"remote_support": 180.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 250.0, "design_ux": 155.0, "pc_setup": 275.0}', 'Onboard: Standard  |  State government and logistics corridor. CoL moderately above national. Government clients may require specific compliance (CJIS). Mid-range pricing appropriate.', 'imported', now()),
  ('CO', 'Denver', 121.0, 72000.0, 7.1, 'standard', 1.0775, '{"remote_support": 170.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 235.0, "design_ux": 150.0, "pc_setup": 275.0}', 'Onboard: Standard  |  Growing tech hub. CoL 21% above national. Competitive MSP market with active cybersecurity awareness. Full-rate to modest premium supportable. Energy sector clients often have OT/ICS needs.', 'imported', now()),
  ('CT', 'Norwalk', 143.0, 91000.0, 3.7, 'premium', 1.155, '{"remote_support": 190.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 265.0, "design_ux": 165.0, "pc_setup": 275.0}', 'Onboard: Standard  |  NYC metro corridor (Fairfield County). CoL 43% above national. Financial services and professional services buyers are sophisticated — compete on compliance depth (SOC 2, PCI, SEC) and 24x5 coverage. Low unemployment signals healthy SMB market.', 'imported', now()),
  ('FL', 'Miami', 123.0, 47000.0, 8.3, 'standard', 1.0, '{"remote_support": 175.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 240.0, "design_ux": 150.0, "pc_setup": 275.0}', 'Onboard: Standard  |  High CoL (23% above national) but paradoxically low median income — large wealth disparity between international finance clients and general population. Target upper-market finance, legal, and healthcare firms. International trade clients have cross-border compliance needs (FinCEN, AML).', 'imported', now()),
  ('FL', 'Tampa', 101.0, 62000.0, 4.5, 'standard', 1.0, '{"remote_support": 155.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 210.0, "design_ux": 135.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Growing SMB market with major healthcare system presence (BayCare, AdventHealth, Moffitt). CoL right at national average. No state income tax. Healthcare compliance (HIPAA) and cyber insurance requirements are primary value drivers. Competitive but growing market.', 'imported', now()),
  ('GA', 'Atlanta', 108.0, 73000.0, 5.3, 'standard', 1.0, '{"remote_support": 160.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 220.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Major Southeast tech and logistics hub. CoL near national average. Growing cybersecurity sector — strong buyer awareness. Delta, Home Depot, UPS, Coca-Cola create large enterprise-adjacent SMB ecosystem. Compete on SOC and MDR depth; market has moved past basic helpdesk competition.', 'imported', now()),
  ('IL', 'Aurora', 106.0, 75000.0, 5.5, 'standard', 1.0, '{"remote_support": 160.0, "onsite_block_2hr": 340.0, "onsite_additional": 170.0, "dev_crm": 220.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Kane/DuPage/Will County — second-largest IL city. CoL 6% above national, solid median income. Diverse economy with strong manufacturing, healthcare (Rush Copley), and growing tech presence. Chicago metro rate with slight adjustment for mixed income profile. Direct Ferrum labor. Good SMB density.', 'imported', now()),
  ('IL', 'Champaign', 89.0, 48000.0, 6.5, 'adjusted', 0.8915, '{"remote_support": 145.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 195.0, "design_ux": 130.0, "pc_setup": 250.0}', 'Onboard: Standard  |  University of Illinois anchors the market. CoL 11% below national. Healthcare (Carle, OSF) and university tech spin-offs are best prospects. Price slightly adjusted from Chicago metro; buyers compare to national academic IT standards.', 'imported', now()),
  ('IL', 'Elgin', 107.0, 88316.0, 6.3, 'standard', 1.0465, '{"remote_support": 160.0, "onsite_block_2hr": 350.0, "onsite_additional": 175.0, "dev_crm": 220.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Chicago suburb. Median HH income $88K and CoL index 107. Treat identically to Chicago market. Strong manufacturing and healthcare base is a compliance upsell opportunity.', 'imported', now()),
  ('IL', 'Frankfort', 108.0, 110000.0, 4.5, 'standard', 1.0465, '{"remote_support": 160.0, "onsite_block_2hr": 350.0, "onsite_additional": 175.0, "dev_crm": 220.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Affluent south suburb. High median income. Treat as Chicago market rate. Professional services and healthcare clients are strong PLUS tier prospects.', 'imported', now()),
  ('IL', 'Geneva', 109.0, 126759.0, 7.1, 'standard', 1.0465, '{"remote_support": 160.0, "onsite_block_2hr": 350.0, "onsite_additional": 175.0, "dev_crm": 220.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Affluent Fox River Valley suburb (Kane County). High median income ($127K). Chicago metro rate fully supported. Professional services and wealth management firms are strong PLUS tier prospects. Direct Ferrum labor.', 'imported', now()),
  ('IL', 'Gurnee', 115.0, 100892.0, 4.8, 'standard', 1.0465, '{"remote_support": 165.0, "onsite_block_2hr": 360.0, "onsite_additional": 180.0, "dev_crm": 230.0, "design_ux": 145.0, "pc_setup": 250.0}', 'Onboard: Standard  |  North shore Lake County suburb. CoL 15% above national, high median income. Retail and manufacturing base. Chicago metro rate fully supported. Lake County industrial corridor offers compliance upsell.', 'imported', now()),
  ('IL', 'Joliet', 93.0, 88026.0, 6.5, 'standard', 1.0, '{"remote_support": 150.0, "onsite_block_2hr": 310.0, "onsite_additional": 155.0, "dev_crm": 200.0, "design_ux": 130.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Will County logistics hub. CoL 7% below national but income is solid ($88K). Near-Chicago rate with slight adjustment. Strong logistics/warehousing sector — PCI and supply chain risk framing effective.', 'imported', now()),
  ('IL', 'Lincolnshire', 120.0, 179735.0, 3.5, 'standard', 1.124, '{"remote_support": 170.0, "onsite_block_2hr": 380.0, "onsite_additional": 190.0, "dev_crm": 235.0, "design_ux": 150.0, "pc_setup": 275.0}', 'Onboard: Standard  |  Affluent Lake County corporate corridor. One of the highest median incomes in the portfolio ($179K). CoL 20% above national. Major corporate HQ presence (Zebra Technologies, CDW, Aon). Premium pricing well-supported.', 'imported', now()),
  ('IL', 'Lisle', 112.0, 90000.0, 4.5, 'standard', 1.0465, '{"remote_support": 165.0, "onsite_block_2hr": 360.0, "onsite_additional": 180.0, "dev_crm": 225.0, "design_ux": 145.0, "pc_setup": 250.0}', 'Onboard: Standard  |  DuPage County tech and corporate corridor (NICOR, Molex, IL Tool Works nearby). CoL 12% above national, solid income. Treat as Chicago metro rate. Strong professional services and tech-adjacent buyer base. Direct Ferrum labor.', 'imported', now()),
  ('IL', 'Naperville', 133.0, 136000.0, 4.2, 'standard', 1.124, '{"remote_support": 180.0, "onsite_block_2hr": 410.0, "onsite_additional": 205.0, "dev_crm": 250.0, "design_ux": 155.0, "pc_setup": 275.0}', 'Onboard: Standard  |  Wealthiest large suburb in IL portfolio ($136K+ median income, CoL 33% above national). DuPage County powerhouse — Nalco, OfficeMax, Nicor Gas. Buyers are sophisticated and budget-ready. Premium tier pricing well-supported alongside Lincolnshire. Direct Ferrum labor.', 'imported', now()),
  ('IL', 'Peoria', 83.0, 58716.0, 9.0, 'adjusted', 0.8915, '{"remote_support": 140.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 190.0, "design_ux": 125.0, "pc_setup": 225.0}', 'Onboard: Waive/defer  |  Secondary market. Low CoL (83) and high unemployment (9%). Caterpillar-driven manufacturing economy. Price-sensitive buyers. Adjusted rate keeps Ferrum competitive vs. local providers. Lead with ransomware and OT/ICS risk.', 'imported', now()),
  ('IL', 'Rock Falls', 78.0, 50000.0, 8.5, 'secondary', 0.845, '{"remote_support": 140.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 180.0, "design_ux": 120.0, "pc_setup": 225.0}', 'Onboard: Waive/defer  |  Small secondary market on the Rock River. Very low CoL (~78), modest income. Manufacturing and healthcare are the primary buyer segments. Bundle entry-level Essentials with waived onboarding to establish foothold.', 'imported', now()),
  ('IL', 'Rockford', 75.0, 58497.0, 10.1, 'adjusted', 0.8915, '{"remote_support": 135.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 180.0, "design_ux": 120.0, "pc_setup": 225.0}', 'Onboard: Waive/defer  |  Secondary market. 25% below national CoL. Local MSP market ceiling ~$115. Ferrum floor is $109 — price here maintains margin while staying competitive. Waive onboarding on first 2-3 clients to build market presence.', 'imported', now()),
  ('IL', 'Roselle', 108.0, 85000.0, 4.5, 'standard', 1.0465, '{"remote_support": 160.0, "onsite_block_2hr": 350.0, "onsite_additional": 175.0, "dev_crm": 220.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  DuPage/Cook County suburb. CoL slightly above national, solid median income. Bedroom community with professional services and healthcare clients. Chicago metro rate fully supported. Direct Ferrum labor.', 'imported', now()),
  ('IL', 'Schaumburg', 113.0, 93000.0, 4.5, 'standard', 1.0465, '{"remote_support": 165.0, "onsite_block_2hr": 360.0, "onsite_additional": 180.0, "dev_crm": 225.0, "design_ux": 145.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Major Cook County commercial hub — Motorola Solutions, Zurich North America, Woodfield Mall. CoL 13% above national, strong median income ($93K). Dense corporate and SMB environment. Full Chicago metro rate supported. Retail/hospitality clients add PCI compliance upsell. Direct Ferrum labor.', 'imported', now()),
  ('IL', 'Sterling', 78.0, 49000.0, 8.5, 'secondary', 0.845, '{"remote_support": 140.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 180.0, "design_ux": 120.0, "pc_setup": 225.0}', 'Onboard: Waive/defer  |  Small secondary market (Whiteside County). Very low CoL, manufacturing-heavy economy. Adjacent to Rock Falls — treat as a single micro-market. Near-floor pricing necessary to compete. Healthcare compliance and manufacturing cybersecurity are primary value drivers.', 'imported', now()),
  ('IL', 'Wadsworth', 110.0, 95000.0, 4.5, 'standard', 1.0465, '{"remote_support": 165.0, "onsite_block_2hr": 350.0, "onsite_additional": 175.0, "dev_crm": 225.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Lake County suburb. High income market, CoL above national. Treat as Chicago metro rate. Small community — business density is lower; ideal for high-touch relationship selling.', 'imported', now()),
  ('IL', 'Wheaton', 128.0, 105000.0, 4.0, 'standard', 1.0775, '{"remote_support": 175.0, "onsite_block_2hr": 390.0, "onsite_additional": 195.0, "dev_crm": 245.0, "design_ux": 155.0, "pc_setup": 275.0}', 'Onboard: Standard  |  DuPage County seat. CoL 28% above national, high median income ($105K). Strong professional services and corporate base. One of the wealthiest county seats in IL. Buyers expect high-quality service — premium end of Standard tier fully supported. Direct Ferrum labor.', 'imported', now()),
  ('IN', 'Gary', 79.0, 38000.0, 12.5, 'secondary', 0.814, '{"remote_support": 140.0, "onsite_block_2hr": 280.0, "onsite_additional": 140.0, "dev_crm": 185.0, "design_ux": 120.0, "pc_setup": 225.0}', 'Onboard: Waive/defer  |  Severely distressed market. Very low income and high unemployment. Steel industry decline. Approach with caution — focus on healthcare/nonprofit clients with stable funding. Price at near-floor.', 'imported', now()),
  ('IN', 'Indianapolis', 95.0, 53000.0, 5.5, 'standard', 0.969, '{"remote_support": 150.0, "onsite_block_2hr": 320.0, "onsite_additional": 160.0, "dev_crm": 205.0, "design_ux": 130.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Growing Midwest metro. CoL 5% below national. Solid SMB density, growing tech sector. Life sciences and healthcare compliance (HIPAA) is the primary value driver.', 'imported', now()),
  ('MA', 'Newton', 132.0, 179843.0, 3.1, 'premium', 1.2016, '{"remote_support": 180.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 250.0, "design_ux": 155.0, "pc_setup": 275.0}', 'Onboard: Standard  |  Affluent Boston suburb with one of the highest median incomes in the portfolio ($180K). Biotech corridor (proximity to Kendall Square), finance, and professional services. Boston metro MSP market is competitive and sophisticated — buyers compare on compliance depth (HIPAA, SOC 2, SEC) and response SLAs. Premium pricing well-supported.', 'imported', now()),
  ('NV', 'Las Vegas', 105.0, 62000.0, 5.5, 'standard', 1.0465, '{"remote_support": 160.0, "onsite_block_2hr": 380.0, "onsite_additional": 175.0, "dev_crm": 215.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Area 2 surcharge on all on-site labor. Gaming/hospitality clients have extreme PCI-DSS and uptime requirements — strong compliance upsell. CoL near national average but income is moderate. Full rate supported.', 'imported', now()),
  ('TX', 'Dallas', 104.0, 54000.0, 5.5, 'standard', 1.0, '{"remote_support": 160.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 215.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Major Sunbelt metro. CoL near national average; highly competitive MSP market. No state income tax. Tech-sector buyers are security-conscious. Compete on SOC maturity and response SLAs.', 'imported', now()),
  ('TX', 'Houston', 101.0, 53000.0, 5.8, 'standard', 1.0, '{"remote_support": 155.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 210.0, "design_ux": 135.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Largest Texas market. CoL at national average; dense SMB ecosystem. Energy sector clients have OT/ICS exposure and cyber insurance requirements — strong upsell for PLUS tier.', 'imported', now()),
  ('TX', 'Richardson', 104.0, 95000.0, 5.8, 'standard', 1.0465, '{"remote_support": 160.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 215.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Telecom Corridor suburb of Dallas. High-income tech hub — median HH income $95K. Telecom, tech, and finance buyers are security-sophisticated. Full rate fully supportable; compete on EDR depth and 24x5 coverage.', 'imported', now()),
  ('WA', 'Seattle', 150.0, 97000.0, 4.5, 'premium', 1.2016, '{"remote_support": 195.0, "onsite_block_2hr": 380.0, "onsite_additional": 175.0, "dev_crm": 275.0, "design_ux": 170.0, "pc_setup": 300.0}', 'Onboard: Standard  |  Area 2 surcharge on all on-site labor. Major tech hub — Amazon, Microsoft ecosystem creates highly security-conscious buyers. CoL 50% above national. Premium pricing well-supported. Compete on EDR/MDR depth and cloud security expertise.', 'imported', now()),
  ('WI', 'Madison', 111.0, 65000.0, 4.5, 'standard', 1.0, '{"remote_support": 165.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 225.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  State capital and university city. CoL 11% above national. Government and university clients may require specific compliance. Growing tech startup scene. Mid-tier pricing appropriate.', 'imported', now()),
  ('WI', 'Milwaukee', 94.0, 49733.0, 6.5, 'adjusted', 0.9225, '{"remote_support": 150.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 200.0, "design_ux": 130.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Largest WI market but modest income ($49K). CoL 6% below national. Healthy SMB density in manufacturing and healthcare. Slightly adjusted rate positions Ferrum competitively. HIPAA and ransomware risk framing effective.', 'imported', now()),
  ('AR', 'Hot Springs', 84.0, 48000.0, 6.5, 'secondary', 0.845, '{"remote_support": 145.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 190.0, "design_ux": 125.0, "pc_setup": 250.0}', 'Onboard: Waive/defer  |  Deep secondary market. State CoL ~84, tourism-dependent local economy. Healthcare and government employers anchor stability. Price at near-floor; risk/compliance framing (HIPAA for healthcare, PCI for hospitality) is the most effective opening. Small but loyal SMB community — referrals drive growth here.', 'imported', now()),
  ('CA', 'Bakersfield', 111.0, 65000.0, 7.5, 'standard', 1.0, '{"remote_support": 165.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 225.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Inland CA agricultural and energy hub. CoL ~11% above national but modest income. Oil/gas sector clients have OT/ICS exposure and cyber insurance needs — strong upsell angle. No Bay Area premium; treat similarly to TX/CO energy markets. Competitive but smaller MSP footprint than coastal CA.', 'imported', now()),
  ('CO', 'Colorado Springs', 110.0, 66000.0, 5.5, 'standard', 1.0, '{"remote_support": 165.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 225.0, "design_ux": 140.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Second-largest CO city. Heavy DoD and military presence (Fort Carson, NORAD, Space Command) creates strong CMMC and federal compliance demand. CoL slightly above national. Tech sector growing. Defense-adjacent SMBs need CMMC Level 1-2 support — strong differentiator vs. generalist MSPs.', 'imported', now()),
  ('ID', 'Boise', 112.0, 65000.0, 4.0, 'standard', 1.0, '{"remote_support": 165.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 225.0, "design_ux": 145.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Fast-growing tech hub (Micron, HP, Clearwater Analytics). CoL 12% above national and rising rapidly. Low unemployment. Strong SMB density with growing cybersecurity awareness. Buyers are increasingly sophisticated — compete on MDR depth. Market is still less saturated than Seattle/Denver.', 'imported', now()),
  ('IA', 'Davenport', 87.0, 54000.0, 5.5, 'adjusted', 0.8915, '{"remote_support": 145.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 195.0, "design_ux": 125.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Quad Cities anchor city (IA side). CoL 13% below national. Manufacturing and healthcare dominate. John Deere HQ creates strong industrial/OT cybersecurity awareness. Slightly adjusted rate appropriate; buyers are pragmatic and ROI-focused. Cross-border market with Rock Island/Moline, IL.', 'imported', now()),
  ('IA', 'Hudson', 85.0, 72000.0, 4.5, 'adjusted', 0.8915, '{"remote_support": 145.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 190.0, "design_ux": 125.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Small Iowa community (Black Hawk County) — not Hudson, WI. CoL ~85, modest income for the area. Manufacturing and agriculture-adjacent professional services are primary prospects. Waterloo/Cedar Falls metro proximity means competition from regional MSPs. Near-adjusted pricing warranted.', 'imported', now()),
  ('LA', 'New Orleans', 96.0, 49000.0, 7.5, 'adjusted', 0.9225, '{"remote_support": 150.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 205.0, "design_ux": 130.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Unique cultural and economic market. CoL near national average but median income is low. Tourism/hospitality and port/maritime industries have strong PCI and operational continuity needs. Healthcare (Ochsner, LCMC) is the most reliable buyer segment. Post-Katrina resilience culture makes business continuity an easy sell.', 'imported', now()),
  ('MI', 'Grand Rapids', 95.0, 57000.0, 4.5, 'standard', 0.969, '{"remote_support": 150.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 205.0, "design_ux": 130.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Second-largest MI city and growing. CoL 5% below national, low unemployment. Strong healthcare presence (Spectrum, Corewell) and diverse manufacturing base. Steelcase, Meijer create enterprise-adjacent SMB ecosystem. Buyers are pragmatic Midwesterners — lead with ROI and operational stability.', 'imported', now()),
  ('MI', 'Kalamazoo', 89.0, 48000.0, 5.5, 'adjusted', 0.9225, '{"remote_support": 145.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 195.0, "design_ux": 130.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Pfizer birthplace and pharma corridor. CoL 11% below national. Life sciences and healthcare buyers have strong HIPAA and data-protection needs — excellent upsell for PLUS tier. Western Michigan University creates education-adjacent IT demand. Slightly adjusted rate appropriate.', 'imported', now()),
  ('MI', 'Lansing', 90.0, 49000.0, 6.5, 'adjusted', 0.9225, '{"remote_support": 145.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 195.0, "design_ux": 130.0, "pc_setup": 250.0}', 'Onboard: Standard  |  State capital — government and quasi-government anchor the market. CoL 10% below national. GM and auto-adjacent manufacturing supply chain present. Government buyers move slowly but are stable accounts. Compliance framing (CJIS for government, HIPAA for healthcare) is the most effective entry.', 'imported', now()),
  ('MN', 'Minneapolis', 103.0, 63000.0, 4.5, 'standard', 1.0, '{"remote_support": 155.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 215.0, "design_ux": 135.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Major Midwest financial and healthcare hub (UnitedHealth, Target, Best Buy HQ). CoL near national average. Competitive MSP market with sophisticated buyers. Strong compliance demand (SOX for finance, HIPAA for healthcare). Low unemployment signals healthy SMB market — compete on 24x5 coverage and MDR depth.', 'imported', now()),
  ('MO', 'St. Louis', 88.0, 50000.0, 5.5, 'adjusted', 0.9225, '{"remote_support": 145.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 195.0, "design_ux": 125.0, "pc_setup": 250.0}', 'Onboard: Standard  |  NOTE: Listed as ''St Louis, IL'' — the major metro is St. Louis, MO (city proper sits in MO; metro spans both states). CoL 12% below national. Strong healthcare (BJC, SSM Health) and financial services base. Washington University and SLU create knowledge-economy adjacency. Adjusted rate appropriate for city-proper; suburban MO markets can support near-standard rates.', 'imported', now()),
  ('OR', 'Portland', 128.0, 75000.0, 5.5, 'premium', 1.155, '{"remote_support": 175.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 245.0, "design_ux": 155.0, "pc_setup": 275.0}', 'Onboard: Standard  |  NOTE: Listed as ''Portland, WA'' — Portland is in Oregon (OR). CoL 28% above national. Nike, Adidas, Intel, and strong healthcare presence (OHSU, Providence). Growing cybersecurity market — buyers are tech-literate and compare on stack depth. No state income tax in WA pulls some buyers across river to Vancouver, WA.', 'imported', now()),
  ('UT', 'Salt Lake City', 121.0, 58000.0, 3.0, 'standard', 1.0, '{"remote_support": 170.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 235.0, "design_ux": 150.0, "pc_setup": 275.0}', 'Onboard: Standard  |  Silicon Slopes tech hub (Adobe, Qualtrics, Domo, Goldman Sachs). CoL 21% above national. Very low unemployment. Fast-growing tech ecosystem with strong cybersecurity awareness. Buyers are younger and tech-literate — compete on EDR/MDR depth and cloud security expertise. Healthcare and finance compliance upsell effective.', 'imported', now()),
  ('WI', 'Platteville', 82.0, 44000.0, 5.0, 'secondary', 0.845, '{"remote_support": 140.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 185.0, "design_ux": 125.0, "pc_setup": 225.0}', 'Onboard: Waive/defer  |  Small UW-Platteville college town in rural SW Wisconsin. Very low CoL (~82), modest income. Limited SMB density — agriculture and university are primary anchors. Near-floor pricing required. Long-term play: university IT spin-offs and ag-tech startups may create demand over time.', 'imported', now()),
  ('WI', 'Racine', 88.0, 50000.0, 7.5, 'adjusted', 0.9225, '{"remote_support": 145.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 195.0, "design_ux": 125.0, "pc_setup": 250.0}', 'Onboard: Standard  |  Lake Michigan manufacturing city (SC Johnson HQ). CoL 12% below national, high unemployment. Manufacturing is the dominant industry — OT/ICS cybersecurity and ransomware protection are primary value drivers. Proximity to Chicago/Milwaukee means buyers compare against metro MSPs. Adjusted rate keeps Ferrum in range.', 'imported', now()),
  ('AZ', 'Tucson', 96.0, 50000.0, 6.0, 'adjusted', 0.9225, '{"remote_support": 150.0, "onsite_block_2hr": 295.0, "onsite_additional": 135.0, "dev_crm": 205.0, "design_ux": 130.0, "pc_setup": 250.0}', 'Onboard: Standard  |  University of Arizona and Davis-Monthan AFB anchor the market. CoL near national average but income is modest. Military/defense clients create CMMC compliance demand. Healthcare (Banner, TMC) is reliable. More price-sensitive than Phoenix — adjusted rate appropriate for competitive positioning.', 'imported', now())
ON CONFLICT (city, state) DO UPDATE SET
  col_index          = EXCLUDED.col_index,
  median_income      = EXCLUDED.median_income,
  unemployment_rate  = EXCLUDED.unemployment_rate,
  market_tier        = EXCLUDED.market_tier,
  pricing_multiplier = EXCLUDED.pricing_multiplier,
  rates              = EXCLUDED.rates,
  market_notes       = EXCLUDED.market_notes,
  analysis_source    = EXCLUDED.analysis_source,
  analyzed_at        = EXCLUDED.analyzed_at,
  updated_at         = now();

-- 5. Verify
SELECT state, city, market_tier, pricing_multiplier, 
       (rates->>'remote_support')::numeric as remote_rate
FROM market_rate_analyses 
ORDER BY col_index DESC 
LIMIT 10;
